name: Data Preprocessing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_SML }}

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn scikit-learn joblib

      - name: Run Preprocessing
        run: |
          python preprocessing/automate_FinaNoviantika.py \
            --file_path dataset_raw/student_habits_performance.csv \
            --target_column exam_score \
            --save_path preprocessing/dataset_preprocessing

      - name: Save file to GITHUB Repository
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add preprocessing/dataset_preprocessing || echo "Nothing to add"

          # Hanya commit jika ada perubahan
          if git diff --cached --quiet; then
            echo "⚠️ Tidak ada perubahan untuk di-commit."
          else
            git commit -m "Add preprocessing output files"
            git push origin main
          fi
