name: Data Preprocessing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn scikit-learn joblib

      - name: Run Preprocessing
        run: |
          python preprocessing/automate_FinaNoviantika.py \
            --file_path dataset_raw/student_habits_performance.csv \
            --target_column exam_score \
            --save_path preprocessing/dataset_preprocessing

      - name: Cek Output File
        run: |
          if [ -f "preprocessing_output/processed_data.csv" ]; then
            echo "✅ File processed_data.csv berhasil dibuat."
          else
            echo "❌ File processed_data.csv tidak ditemukan."
            exit 1
          fi
