name: Preprocess Dataset

on:
  push:
    branches:
      - main 

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn scikit-learn joblib

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_FinaNoviantika.py \
            --file_path dataset_raw/student_habits_performance.csv \
            --target_column exam_score \
            --save_path preprocessing/dataset_preprocessing
